### ISSUE TITLE
zigbee2mqtt and smart button

### ISSUE THREAD

**Issue by djmalin** [so3n/Appdaemon-Xiaomi-Smart-Button#1]
is this button enabled by zigbee2mqtt and not by xiaomi gateway?

detects mqtt integrations but doesn't work when in conf
buttons: sensor.0x00158d0003e7c580_click - integration via mqtt it doesn't work and when it changes
buttons: binary_sensor.switch_158d0003e7c580 - integration with xiaomi gateway this button works, is it possible to bypass the xiaomi gateway?

**Comment by nickneos** [comment]
This app requires xiaomi gateway.

This app listens to the [event](https://www.home-assistant.io/docs/configuration/events/) type `xiaomi_aqara.click` which I guess is different for zigbee2mqtt.

I don't use zigbee2mqtt so not sure how it works.
